apiVersion: shipwright.io/v1alpha1
kind: Build
metadata:
  namespace: build-examples-alpha
  name: ko-build
spec:
  paramValues:
    - name: go-flags
      value: '-v -mod=vendor -ldflags=-w'
    - name: go-version
      value: '1.17'
    - name: package-directory
      value: ./cmd/shipwright-build-controller
  source:
    url: https://github.com/shipwright-io/build
  strategy:
    name: ko
    kind: BuildStrategy
  output:
    image: image-registry.openshift-image-registry.svc:5000/build-examples-alpha/ko-build
---
apiVersion: shipwright.io/v1alpha1
kind: BuildRun
metadata:
  namespace: build-examples-alpha
  generateName: ko-build-
spec:
  buildRef:
    name: ko-build
---
apiVersion: shipwright.io/v1alpha1
kind: BuildRun
metadata:
  namespace: build-examples-alpha
  generateName: ko-build-
spec:
  buildRef:
    name: ko-build
