apiVersion: shipwright.io/v1beta1
kind: BuildRun
metadata:
  generateName: buildpack-nodejs-buildrun-
spec:
  build:
    spec:
      source:
        type: Git
        git:
          url: https://github.com/shipwright-io/sample-nodejs
        contextDir: source-build
      strategy:
        kind: BuildStrategy
        name: buildpacks-v3
      output:
        image: image-registry.openshift-image-registry.svc:5000/christoph/buildpack-nodejs-build:latest
